#     ___           __             _____                               _____          ____
#    / _ \___  ____/ /_____ ____  / ___/__  __ _  ___  ___  ___ ___   / ___/__  ___  / _(_)__ _
#   / // / _ \/ __/  '_/ -_) __/ / /__/ _ \/  ' \/ _ \/ _ \(_-</ -_) / /__/ _ \/ _ \/ _/ / _ `/
#  /____/\___/\__/_/\_\\__/_/    \___/\___/_/_/_/ .__/\___/___/\__/  \___/\___/_//_/_//_/\_, /
#                                              /_/                                      /___/
version: "3.1"
services:

  #
  #
  # Nginx
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - ./docker/nginx/conf:/etc/nginx/conf.d/
        - ./docker/nginx/ssl:/etc/nginx/ssl
        - ./docker/logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
      build: ./docker/nginx/
      links:
        - wordpress
      restart: always

  #
  #
  # MySQL
  mysql:
      image: mariadb
      container_name: mysql
      ports:
        - '3306:3306'
      volumes:
        - ./docker/db-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
      restart: always

  #
  #
  # Wordpress
  wordpress:
      image: wordpress:4.9.0-php7.1-fpm
      container_name: wordpress
      ports:
        - '9000:9000'
        - '4000:4000'
      volumes:
        - ./base-theme/:/var/www/html/wp-content/themes/base-theme/
      environment:
        - WORDPRESS_DB_NAME=wp_wordpress
        - WORDPRESS_TABLE_PREFIX=px_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=root
      links:
        - mysql
      restart: always